import js from '@eslint/js'
import tseslint from 'typescript-eslint'
import reactHooks from 'eslint-plugin-react-hooks'
import prettier from 'eslint-config-prettier'

export default tseslint.config(
  {
    ignores: [
      'node_modules/**',
      'dist/**',
      'src-tauri/target/**',
      'test/dummy-astro-project/**',
      'test/demo-project/**',
      'test/starlight-minimal/**',
      'temp-dummy-astro-project/**',
      'src-tauri/src/test_fixtures/**',
      '*.config.{js,ts}',
      'vite.config.ts',
      'tailwind.config.js',
      'scripts/**',
      'telemetry-worker/**',
      'website/**',
      'website-old/**',
      'src/lib/bindings.ts', // Auto-generated by tauri-specta
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  {
    files: ['src/**/*.{ts,tsx}'],
    plugins: {
      'react-hooks': reactHooks,
    },
    languageOptions: {
      parserOptions: {
        project: './tsconfig.json',
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // React Hooks rules (includes React Compiler rules)
      ...reactHooks.configs['recommended-latest'].rules,

      // TypeScript specific rules
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/explicit-module-boundary-types': 'off',
      '@typescript-eslint/no-explicit-any': 'warn',

      // General rules
      'no-console': 'warn',
      'prefer-const': 'error',
      'no-var': 'error',
    },
  },
  {
    files: ['**/*.js', '**/*.mjs'],
    ...tseslint.configs.disableTypeChecked,
  },
  prettier
)
